services:
  iam-keycloak-01:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: iam-01
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - 9090:8080
    restart: unless-stopped

  app-db-01:
    image: postgres:16-bookworm-slim
    container_name: app-db-01
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - kc_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped